# Generated by Django 4.0.3 on 2023-07-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0003_link_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='Anonymous', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clicked_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.link')),
            ],
        ),
    ]
