# Generated by Django 4.0.3 on 2022-03-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newurl',
            name='shortcode',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newurl',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
