# Generated by Django 4.0.3 on 2022-03-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_newurl_created_newurl_shortcode_newurl_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newurl',
            old_name='update',
            new_name='updated',
        ),
    ]
