# Generated by Django 4.0.3 on 2022-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_update_newurl_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
