# Generated by Django 4.0.3 on 2022-03-22 14:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_newurl_shortcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newurl',
            managers=[
                ('alternate', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='newurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
