# Generated by Django 4.0.3 on 2022-03-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_newurl_managers_newurl_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newurl',
            managers=[
            ],
        ),
    ]
