# Generated by Django 4.0.3 on 2023-07-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newurl',
            new_name='Link',
        ),
    ]
